# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Abimereki Muzaale
author: jhustsata
logo: https://cdn.jamanetwork.com/ama/content_public/journal/jama/929765/joi130123f1.png?Expires=1683793256&Signature=UY3XSHhpgEpSpK1x~wqLYS1CaWa0Itb6SDDkvZ9DYIi2UFQD02~xAm3~tKO3u265eNC6jwa3PEiUQL-OXEi0OB5verUwcT2YNpMa-9kdgbqNfvpdVC5Yg7gXNnPcqgvGuWwQEr8eFMpen-W8Foft0tv7Xujzqai1G09a~Ndm43TjzJJnhUkznJ6N93sjc-AOoqj0Tv8QKw7K4syVCSGZZ-AhYyK~Y9Y2zChTbwCZpzbQhQ~3s7bASF7Hq5NFNM7Q-2JU9iN-7hi6HcjaQwLqUrZaS6DqNw~c6Yw5zVr5ggCvrYu94w9yg6H-VgLYJQ3s5-kijqgiDqhvnDQfOTjc0A__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
